/**
 * Share Button Component
 *
 * Allows users to share or export their career results.
 * Supports native share API, clipboard copy, and PDF export.
 */

import { useState, useCallback } from 'react';
import type { CareerRole, Location, LocationInsights } from '../types';
import styles from './ShareButton.module.css';

interface ShareButtonProps {
  role: CareerRole;
  location: Location;
  matchPercentage: number;
  insights?: LocationInsights | null;
}

type ShareOption = 'native' | 'copy' | 'download';

export function ShareButton({
  role,
  location,
  matchPercentage,
  insights,
}: ShareButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateShareText = useCallback(() => {
    let text = `🎯 My PathForge Career Match Results\n\n`;
    text += `Role: ${role.title}\n`;
    text += `Match: ${matchPercentage}%\n`;
    text += `Location: ${location.flag} ${location.name}\n\n`;

    if (insights) {
      text += `💰 Salary: ${insights.salaryRange}\n`;
      text += `📈 Demand: ${insights.demandLevel === 'high' ? 'High' : insights.demandLevel === 'growing' ? 'Growing' : 'Moderate'}\n\n`;
    }

    text += `Key Skills:\n`;
    role.skills.slice(0, 5).forEach((skill) => {
      text += `• ${skill}\n`;
    });

    text += `\n🔗 Find your career path at PathForge`;

    return text;
  }, [role, location, matchPercentage, insights]);

  const generateMarkdown = useCallback(() => {
    let md = `# PathForge Career Analysis\n\n`;
    md += `## Your Best Match: ${role.title}\n\n`;
    md += `**Match Score:** ${matchPercentage}%\n`;
    md += `**Target Location:** ${location.flag} ${location.name}\n\n`;

    if (insights) {
      md += `### Market Insights\n\n`;
      md += `| Metric | Value |\n`;
      md += `|--------|-------|\n`;
      md += `| Salary Range | ${insights.salaryRange} |\n`;
      md += `| Demand Level | ${insights.demandLevel === 'high' ? '🟢 High' : insights.demandLevel === 'growing' ? '🟡 Growing' : '🟠 Moderate'} |\n\n`;

      if (insights.topEmployers?.length > 0) {
        md += `### Top Employers in ${location.name}\n\n`;
        insights.topEmployers.forEach((employer) => {
          md += `- ${employer}\n`;
        });
        md += `\n`;
      }

      if (insights.jobMarketTrends) {
        md += `### Market Trends\n\n`;
        md += `${insights.jobMarketTrends}\n\n`;
      }
    }

    md += `### About the Role\n\n`;
    md += `${role.overview}\n\n`;

    md += `### Why This Role Fits You\n\n`;
    role.whyFits.forEach((reason) => {
      md += `- ${reason}\n`;
    });

    md += `\n### Key Skills to Develop\n\n`;
    role.skills.forEach((skill) => {
      md += `- ${skill}\n`;
    });

    md += `\n### Recommended Tools\n\n`;
    role.tools.forEach((tool) => {
      md += `- ${tool}\n`;
    });

    md += `\n### Certifications\n\n`;
    role.certifications.slice(0, 4).forEach((cert) => {
      md += `- **${cert.name}** (${cert.provider}) - ${cert.level}\n`;
    });

    if (insights?.tips?.length) {
      md += `\n### Tips for ${location.name}\n\n`;
      insights.tips.forEach((tip) => {
        md += `- ${tip}\n`;
      });
    }

    md += `\n---\n*Generated by PathForge - Career Pathway Platform*\n`;

    return md;
  }, [role, location, matchPercentage, insights]);

  const handleShare = async (option: ShareOption) => {
    switch (option) {
      case 'native':
        if (navigator.share) {
          try {
            await navigator.share({
              title: 'My PathForge Career Results',
              text: generateShareText(),
            });
          } catch {
            // User cancelled or error
          }
        }
        break;

      case 'copy':
        try {
          await navigator.clipboard.writeText(generateShareText());
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        } catch {
          // Fallback for older browsers
          const textArea = document.createElement('textarea');
          textArea.value = generateShareText();
          document.body.appendChild(textArea);
          textArea.select();
          document.execCommand('copy');
          document.body.removeChild(textArea);
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        }
        break;

      case 'download':
        const markdown = generateMarkdown();
        const blob = new Blob([markdown], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `pathforge-${role.id}-${location.id}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        break;
    }

    setIsOpen(false);
  };

  const canShare = typeof navigator !== 'undefined' && 'share' in navigator;

  return (
    <div className={styles.container}>
      <button
        className={styles.shareButton}
        onClick={() => setIsOpen(!isOpen)}
        aria-label="Share results"
        aria-expanded={isOpen}
      >
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M8.59 13.51L15.42 17.49M15.41 6.51L8.59 10.49M21 5C21 6.65685 19.6569 8 18 8C16.3431 8 15 6.65685 15 5C15 3.34315 16.3431 2 18 2C19.6569 2 21 3.34315 21 5ZM9 12C9 13.6569 7.65685 15 6 15C4.34315 15 3 13.6569 3 12C3 10.3431 4.34315 9 6 9C7.65685 9 9 10.3431 9 12ZM21 19C21 20.6569 19.6569 22 18 22C16.3431 22 15 20.6569 15 19C15 17.3431 16.3431 16 18 16C19.6569 16 21 17.3431 21 19Z"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
        Share
      </button>

      {isOpen && (
        <>
          <div className={styles.backdrop} onClick={() => setIsOpen(false)} />
          <div className={styles.dropdown}>
            <div className={styles.dropdownHeader}>Share Your Results</div>

            {canShare && (
              <button
                className={styles.dropdownItem}
                onClick={() => handleShare('native')}
              >
                <svg
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M4 12V20C4 21.1046 4.89543 22 6 22H18C19.1046 22 20 21.1046 20 20V12M16 6L12 2M12 2L8 6M12 2V15"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
                Share via...
              </button>
            )}

            <button
              className={styles.dropdownItem}
              onClick={() => handleShare('copy')}
            >
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M8 4V16C8 17.1046 8.89543 18 10 18H18C19.1046 18 20 17.1046 20 16V7.24162C20 6.7034 19.7831 6.18789 19.3982 5.81161L16.0833 2.56999C15.7086 2.20322 15.2051 2 14.6851 2H10C8.89543 2 8 2.89543 8 4Z"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
                <path
                  d="M16 18V20C16 21.1046 15.1046 22 14 22H6C4.89543 22 4 21.1046 4 20V8C4 6.89543 4.89543 6 6 6H8"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
              {copied ? 'Copied!' : 'Copy to clipboard'}
            </button>

            <button
              className={styles.dropdownItem}
              onClick={() => handleShare('download')}
            >
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M21 15V19C21 20.1046 20.1046 21 19 21H5C3.89543 21 3 20.1046 3 19V15M17 10L12 15M12 15L7 10M12 15V3"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
              Download as Markdown
            </button>

            <div className={styles.dropdownFooter}>
              Share your career path with mentors, friends, or save for reference
            </div>
          </div>
        </>
      )}
    </div>
  );
}
